[build]
command = "pnpm build"

[build.environment]
NODE_VERSION = "18"

[functions]
directory = ".netlify/functions-internal"

[[redirects]]
from = "/*"
to = "/.netlify/functions/entry"
status = 200
